[package]
edition = "2021"
name = "bevy_novel"
version = "0.15.0"
license = "MIT OR Apache-2.0"
description = "Visual Novels with Bevy"
keywords = ["ai", "visual-novel", "renpy", "rpy"]
repository = "https://github.com/stillonearth/bevy_novel"

[dependencies]
bevy = { version = "0.15" }
regex = "1.11.1"
renpy_parser= "0.0.7"
bevy_kira_audio = { version = "0.21", features = ["ogg", "mp3", "wav"]}

[dev-dependencies]
bevy-inspector-egui = "0.28.0"

[profile.dev]
opt-level = 3
