[package]
edition = "2021"
name = "bevy_rl"
version = "0.14.0"
license = "MIT OR Apache-2.0"
description = "Visual Novels with Bevy"
keywords = ["ai", "bevy", "gym", "rl"]
repository = "https://github.com/stillonearth/bevy_novel"

[dependencies]
bevy = { version = "0.14.0" }
bevy_lunex = { version = "0.2.4" }
bevy-inspector-egui = "0.27.0"
regex = "1.11.1"
renpy_parser= "0.0.1"

[profile.dev]
opt-level = 3
